dist: trusty
sudo: required

language: php

php:
  - 7.1
  - 7.0

env:
  - SYMFONY_VERSION=3.2.*

before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.1.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.2.1.deb
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install -b mapper-attachments
  - sudo service elasticsearch restart
  - sleep 15
  - travis_retry composer self-update

services:
  - elasticsearch

install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter
  - bash <(curl -s https://codecov.io/bash)
